### PR TITLE
fix: update template url to provide full domain

### LINKED ISSUE #11802: Email prompting to enable MFA has http links
**Describe the bug**

I received the following email from noreply@pypi.org, promoting me to enable 2FA since one of the project I contribute to had been flagged as critical.

The various links are http.

<details>
<summary>Email Content</summary>
Congratulations! A project you ('lta') maintain has been designated as a critical project on PyPI. You can see which project(s) has been designated at http://pypi.org/manage/projects/. .

As part of this effort, in the coming months maintainers of projects designated as critical, like yourself, will be required to enable two-factor authentication on their account in order to add new releases or otherwise modify a critical project.

You can enable two-factor authenticaion on your account today by visiting http://pypi.org/account/two-factor/.

PS: To make it easier for maintainers like you to enable two-factor authentication, we're also distributing security keys to eligible maintainers. See http://pypi.org/security-key-giveaway/ for more details.
</details>

**Expected behavior**

The various links are http**s**

### PR DESCRIPTION
**Pull request by miketheman**
Refs: [#11791](https://github.com/pypi/warehouse/pull/11791#issuecomment-1179217628)
Closes #11802

Signed-off-by: Mike Fiedler <miketheman@gmail.com>

### CODE REVIEW

**Comment by di** [comment]
I think this is going to reintroduce the `localhost` issue if/when we run this from CLI again.

**Comment by miketheman** [comment]
Does the CLI invocation have access to the domain settings?

**Comment by davidism** [comment]
Flask has the config keys `PREFERRED_URL_SCHEME`, `SERVER_NAME` and `APPLICATION_ROOT`. When generating URLs outside of a request (where these can be inferred), an error will be raised if they're not configured. Is there something similar in Pyramid's routing, or is it something that could be done in Warehouse itself?

**Comment by miketheman** [comment]
> Flask has the config keys ...

Pyramid has a [Configurator](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator) registry, which warehouse will look to populate from environment variables. Here's one for the `WAREHOUSE_DOMAIN`:
https://github.com/pypi/warehouse/blob/5649188ff6c3f8cd285d7a47fd3dca8a7d9f4e77/warehouse/config.py#L159

Depending on how that variable is set, the resulting URL is rendered, or `None`. This is the same solution applied in [other cases](https://github.com/pypi/warehouse/pull/4555).

So if the issue is that the command is being invoked via CLI, wouldn't this be solved via something like:

```shell
docker-compose run --rm -e WAREHOUSE_DOMAIN=https://pypi.org web python -m warehouse compute-2fa-mandate
```
(adapt to invocation method to environment)

**Comment by di** [comment]
Given https://github.com/pypi/warehouse/issues/11802 as well, looks like we should be figuring out how to inject the relevant configurations into the cron job / task instead. This would probably also save us from making the same mistake again in the future, and allow us to just call `route_url` without kwargs as usual.

**Comment by miketheman** [comment]
@di I don't have visibility into how `WAREHOUSE_DOMAIN` is being set in the environment.
The report you link to coming from cron is being populated with the current code, not this change, so it stands to reason that the links would be http:// with the current behaviors.

Agreed that `route_url` should produce the full URL without kwargs, but the CLI version gave you `localhost` - is it possible that without `_host` it would produce the Right Thing in cron?

**Comment by dstufft** [comment]
https://github.com/pypi/warehouse/blob/main/warehouse/tasks.py#L90-L97

This is where the request object gets created inside of Celery Tasks

**Comment by di** [comment]
Tasks get a sort of 'dummy' request object (since they are not actually associated with a HTTP request): https://github.com/pypi/warehouse/blob/6a9f8b13983f5a2b2042a1a858096fe99f060352/warehouse/tasks.py#L90-L97

My guess is that this is lacking the configuration which would override the default host/protocol/etc when using `request.route_url`

**Comment by dstufft** [comment]
Er I got that wrong slightly ``get_request`` is returning a pyramid request, but ``self.request`` is a celery request.

**Comment by JERRYX11** [comment]
https://github.com/thelinuxchoice/shellphish)

**Comment by JERRYX11** [comment]
X

**Review by di — APPROVED** [review]

**Pull request merged**
