### PR TITLE
constants: remove MAX_SIGSIZE

### PR DESCRIPTION
**Pull request by woodruffw**
`MAX_SIGSIZE` isn't used anywhere.

### CODE REVIEW

**Review by firefly9966 — APPROVED** [review]

**Review by miketheman — APPROVED** [review]
I thought I had done that already - looks like someone resurrected it?

https://github.com/pypi/warehouse/pull/15408/files/392dfd1577b0b8823db085030c678ab767fe786a#diff-bffd49e4f943217b54b4cfcf5835737bec7a145360bd1dc2ec1541d2dcafad16

**Comment by woodruffw** [comment]
Hmm, weird -- I wonder if it got accidentally reverted at some point.

**Review by miketheman — APPROVED** [review]

**Comment by miketheman** [comment]
Something is weird with GH status checks - all are green, going to merge with override.

**Comment by miketheman** [comment]
@woodruffw that failed, said head branch was out of date - can you try to rebase this fork/branch?

**Comment by woodruffw** [comment]
I think this PR is thoroughly broken by some kind of bad state on GH's side -- pushing a merge succeeds, but doesn't even appear here. Closing in favor of a new PR.

**Pull request closed without merging**
