### PR TITLE
Document Metadata fields and format for the Upload API

### PR DESCRIPTION
**Pull request by alanbato**
This should fix the problem stated in #3151.
This is a WIP and the changes [mentioned here](https://github.com/pypa/warehouse/issues/3151#issuecomment-377973307) have not been added yet.

Any comments/ideas/questions on the format and content are welcome :smiley: 

PS. `make docs` isn't working for me, it complains about sphinx not being installed inside the venv :sweat_smile: 

Pinging @brainwane and @di for review.

:snake: :package: :memo:

### CODE REVIEW

**Comment by brainwane** [comment]
For reference -- we chatted about this [in today's Warehouse livechat](http://kafka.dcpython.org/day/pypa-dev/2018-04-03).

**Comment by brainwane** [comment]
@alanbato How's this going?

**Comment by abitrolly** [comment]
I think this should be merged. It improves API documentation a lot. Validation and corrections can be added in a separate `good first issue`.

**Comment by abitrolly** [comment]
@di is it possible to reticket description of dependency fields as a separate issue? There are a lot of questions about them. Like if they are stored, then where they are  exposed in API, why we still need #8254, etc.

**Comment by dstufft** [comment]
There is now [PEP 694: Upload 2.0 API for Python Package Repositories](https://peps.python.org/pep-0694/), which has discussions on [discuss.python.org](https://discuss.python.org/t/pep-694-upload-2-0-api-for-python-package-repositories/16879) which is relevant to this issue.

**Comment by di** [comment]
Closing this in favor of eventually documenting this via a PEP, like https://peps.python.org/pep-0694/.

**Comment by abitrolly** [comment]
@di maybe close this when the documentation is done? Otherwise there is no way to track it.

**Comment by di** [comment]
This is being tracked in #3151.

**Pull request closed without merging**
