### PR TITLE
docs: internal docs for trusted publishers

### LINKED ISSUE #13470: Document why trusted publishing uses a "two phase" token exchange system
This is something that's come up (reasonably!) as a question from other package indices looking to integrate OIDC for trusted publishing.

### PR DESCRIPTION
**Pull request by woodruffw**
This adds an "Internals and Technical Details" page with both a high-level description of how trusted publishing works and a Q&A section with some pre-filled Q&As on the design of trusted publishing.

Closes #13470.

CC @di

### CODE REVIEW

**Comment by miketheman** [comment]
**question:** ‏seeing as these are internal docs, should they be placed in [a dev docs section](https://github.com/pypi/warehouse/tree/main/docs/dev/development) instead?

**Comment by woodruffw** [comment]
> **question:** ‏seeing as these are internal docs, should they be placed in [a dev docs section](https://github.com/pypi/warehouse/tree/main/docs/dev/development) instead?

Possibly -- I wrote these more as "retrospective" details (for other package indices to benefit from) rather than concrete implementation details that would help a Warehouse contributor, but I have no strong opinion on where they actually belong :slightly_smiling_face:

**Comment by makansissoko** [comment]
Le fonds extérieur

**Review by di — APPROVED** [review]
We've gotten enough questions about this from regular users that I'm OK with them living in the user docs.

**Pull request merged**
