### PR TITLE
chore(dev): cache generated artifacts between runs

### LINKED ISSUE #13019: Use mypy's SQLite cache option?
Typechecking Warehouse with `make lint` can be pretty slow; `mypy`'s `sqlite-cache = true` setting would probably slow it up a bit.

I can do this, just creating an issue first for visibility/in case there's a known reason not to do this 🙂

### PR DESCRIPTION
**Pull request by miketheman**
Closes #13019

### CODE REVIEW

**Comment by ewdurbin** [comment]
Non blocker, but is this cacheable in CI as well?

**Review by ewdurbin — APPROVED** [review]

**Comment by miketheman** [comment]
> is this cacheable in CI as well?

It's entirely possible, but not through this mechanism, as our CI doesn't use Docker Compose.

Considering the CI runs slowest step is still `tests` due to parallelism, is it worth it?

**Review by woodruffw — APPROVED** [review]
Nice, thanks @miketheman!

**Comment by ewdurbin** [comment]
> Considering the CI runs slowest step is still `tests` due to parallelism, is it worth it?

From a pure stewardship perspective, I think any reduction in execution time are worth seeing through!

**Comment by miketheman** [comment]
> 

Fair enough - started https://github.com/pypi/warehouse/pull/13021

**Comment by di** [comment]
Just noticed that this allows us to use pytest's `--last-failed` and `--failed-first` options! https://docs.pytest.org/en/7.1.x/how-to/cache.html

**Comment by miketheman** [comment]
Yep, that was one of my use cases, sorry for not calling that out louder!

**Pull request merged**
