### PR TITLE
Fix bug adding team collaborator (#12229)

### PR DESCRIPTION
**Pull request by sterbo**
- Adding a team collaborator to a project in an org leads to an error

### CODE REVIEW

**Comment by miketheman** [comment]
@sterbo suggestion: in your commit/PR description, use the syntax "Fixes #NNN" so that once merged, it auto-closes.
More on this here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by miketheman** [comment]
Fixes #12229

**Review by ewdurbin — APPROVED** [review]
able to reproduce and validate fix. thanks.

**Comment by ewdurbin** [comment]
Resolves #12229

**Pull request merged**
