### PR TITLE
Don't show org removal on non-org project, use DISABLE_ORGANIZATION for transfer/org removal

### PR DESCRIPTION
**Pull request by jack1142**
Reported in Discord, both of these get shown on individual projects on PyPI:
image

I've put both of these behind the DISABLE_ORGANIZATION flag and fixed the org removal being shown for non-org (individual) projects.

"Hide whitespace" diff should be more digestable.

### CODE REVIEW

**Comment by miketheman** [comment]
CC @divbzero whom I believe has been working on this.

**Comment by divbzero** [comment]
@miketheman The fix to the condition looks good to me. Thank you @jack1142 for finding and fixing the bug.

**Comment by jack1142** [comment]
Credit for finding goes to @ ichard26 who reported it on PyPA Discord :)

**Review by miketheman — APPROVED** [review]
Looks good to me!

**Review by ewdurbin — APPROVED** [review]

**Comment by ewdurbin** [comment]
Thank you!

**Pull request merged**
