### PR TITLE
feat(admin): set primary email after recovery complete

### LINKED ISSUE #16401: "Start Account Recovery" Process Doesn't Update to Alternate Email Address
**What's the problem this feature will solve?**
Currently, when a user with existing projects requests an email update/change, as part of the account verification process, the "start account recovery" function doesn't automatically update to the user's new/preferred email address after branch verification has been completed. This feature will remove the need for PyPI Support and/or Admin to manually update a user's email address.

**Describe the solution you'd like**
An ideal solution would be: when the account verification process is initiated, if an input for an alternate email exists, the "Complete Recovery" function should also update a user's primary email address to the alternate email address, in addition to its current functionality of resetting the 2FA and recovery codes. 

**Additional context**

### PR DESCRIPTION
**Pull request by miketheman**
If the Account Recovery process has an **alternate** email that is to be used during the process, 'activate' it at the end once completed.

Resolves #16401

### CODE REVIEW

**Comment by ewdurbin** [comment]
I think this fits the need. One thought that I hadn't really considered is if we should skip password/2FA reset in these conditions. My understanding is that _generally_ this state occurs when someone has their password/2FA but has lost access to the original primary email address.

@Thespi-Brain, do you have any input here?

**Comment by Thespi-Brain** [comment]
@ewdurbin I think we should still keep the password/2FA reset because there have been cases where 2FA was not set up in addition to the user not having access to their original primary email address. It's also nice to have a "clean" reset for due diligence and security.

**Review by ewdurbin — APPROVED** [review]
@Thespi-Brain I am assuming that for situations where users still control their password/2FA, we will update their email address without resetting password/2FA. If so this is good to go.

**Comment by Thespi-Brain** [comment]
@ewdurbin Yes, we only don't go through the account recovery process for an email update when the user either (a) doesn't have 2FA/recovery codes or (b) when a user doesn't have any projects

**Pull request merged**
