### PR TITLE
Prefer `InputRequired` over `DataRequired` on form validation

### LINKED ISSUE #13695: Chore: Forms: replace `DataRequired` with `InputRequired`
A bunch of the Warehouse forms use `DataRequired` when they should probably be using `InputRequired`, since the latter is stricter and doesn't do default (probably unintended) input coercions.

Ref: https://wtforms.readthedocs.io/en/2.3.x/validators/#wtforms.validators.DataRequired

Assigning to myself for triage.

### PR DESCRIPTION
**Pull request by jleightcap**
WIP

Resolves #13695

### CODE REVIEW

**Comment by jleightcap** [comment]
The addition of the `MultiDict` import has raised typing stub errors;

```
warehouse/views.py:43: error: Skipping analyzing "webob.multidict": module is installed, but missing library stubs or py.typed marker  [import]
warehouse/accounts/views.py:32: error: Skipping analyzing "webob.multidict": module is installed, but missing library stubs or py.typed marker  [import]
warehouse/accounts/views.py:32: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 2 errors in 2 files (checked 336 source files)
```

Because of the addition `webob.multidict` in the `warehouse/` dir.

**Comment by jleightcap** [comment]
One last error exists, having to do with type coercion of a `datetime` object no longer being performed by the validator,

```
 def test_valid_data(self, banner_data):
        form = views.BannerForm(formdata=MultiDict(banner_data))
        assert form.validate() is True
        data = form.data
        defaults = {
            "fa_icon": Banner.DEFAULT_FA_ICON,
            "active": False,
            "link_label": Banner.DEFAULT_BTN_LABEL,
        }
>       assert data == {**banner_data, **defaults}
# ...
E         Differing items:
E         {'end': datetime.date(2023, 5, 27)} != {'end': '2023-05-27'}
E         Full diff:
E           {
E            'active': False,
E         -  'end': '2023-05-27',
E         +  'end': datetime.date(2023, 5, 27),
E            'fa_icon': 'fa-comment-alt',
E            'link_label': 'See more',
E            'link_url': 'https://samplebanner.com',
E            'name': 'Sample Banner',
E            'text': 'This should be the correct text',
E           }
```

**Comment by miketheman** [comment]
> The addition of the `MultiDict` import has raised typing stub errors;
> ...
> Because of the addition `webob.multidict` in the `warehouse/` dir.

Not all packages have type hints. There's an [open PR on Typeshed for WebOb](https://github.com/python/typeshed/pull/9874) - so our convention has been to add an excluded entry to `pyproject.toml` and drop a link to the PR so we can check on it at a later date.

**Comment by woodruffw** [comment]
@miketheman Guessing you might know this 🙂 -- do you happen to know if there's a way to forbid `DataRequired` in new PRs going forwards? We probably don't want to accidentally regress on this.

**Comment by miketheman** [comment]
> do you happen to know if there's a way to forbid `DataRequired` in new PRs going forwards? We probably don't want to accidentally regress on this.

We currently use Flake8 for linting, so I could imagine a Flake8 Local Plugin that disallows DataRequired. https://flake8.pycqa.org/en/latest/user/configuration.html#using-local-plugins
I haven't done one of these myself yet, but that looks like it might prove useful.

**Comment by woodruffw** [comment]
Looks like https://pypi.org/project/flake8-tidy-imports/ might be a good fit as well for that! I think `ruff` also has similar support.

I'll punt on both of those for this PR, though 🙂

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
Nice work @jleightcap! 

CC @di this should be ready for review now.

**Review by di — APPROVED** [review]

**Pull request merged**
