### PR TITLE
Skip non-user URLs when autodetecting a GitHub repository

### PR DESCRIPTION
**Pull request by Julian**
Uses a hardcoded list of known examples (from a new dependency).

Closes: #12725

### CODE REVIEW

**Comment by Julian** [comment]
(Leaving as draft -- I didn't investigate improving the 404 behavior generally, will see if I get any additional time to do so, though what's here should fix the specific example(s) already)

**Comment by jayaddison** [comment]
I might be able to help out with the error-response handling side of this: after looking at how the frontend handles stats display currently, I've opened #12759, which displays some of the existing code (I'm not sure yet whether the suggested fix is a good one though).

**Comment by Julian** [comment]
Ah amazing, well done, yeah that looks nice!

**Comment by jayaddison** [comment]
Thanks!  The name-filtering approach here looks good, too.  Something probably worth checking: is the `COPYING` file from `github-reserved-names` included when it's built into a package?

**Comment by Julian** [comment]
> is the COPYING file from github-reserved-names included when it's built into a package?

Looks like it is yeah, let me know if you were just asking or if you'd seen it not be included somehow.

**Comment by jayaddison** [comment]
Thanks - I'd taken a look at the [`pyproject.toml` license configuration](https://github.com/Julian/github-reserved-names/blob/228f0fc3c0cb9c6d83c4a6177aab9fd170fb9374/pyproject.toml#L12) and wasn't sure whether the `COPYING` file would be bundled when a `text` license is specified.

The reason I asked is that I noticed you credit the NPM source package -- the correct thing to do -- and I wanted to check that that work and reference is included in the distributed package (and indirectly in `pypi/warehouse` as well).

(I've recently worried about making mistakes related to copyright and attribution in my own projects - and so it was on my mind to check for similar problems elsewhere; even at the risk of seeming like asking difficult questions.  on balance I figured it was better to ask.  in retrospect I probably should've just downloaded the package and checked myself)

**Comment by Julian** [comment]
Ah no worries at all, it's a helpful question! And even with the laziness, better to ask and have me check than stay quiet :D -- yeah don't worry bout that, I'm lazy enough for all of us so I don't mind offloading a bit of it hah.

Anyways, now I don't really understand why CI is complaining about dependencies, so trying to figure out what it expects me to run beyond `pip-compile`.

**Comment by di** [comment]
@Julian Might want to check the version of `pip-tools` you have, I see some extraneous changes here.

**Pull request merged**
