### PR TITLE
docs: add system architecture diagrams

### PR DESCRIPTION
**Pull request by miketheman**
Not 100% comprehensive, but a good starting point.

Related to #2794 

To see generated HTML, run:

```shell
make dev-docs && python -m http.server -d docs/dev/_build/html/
```

and browse to http://localhost:8000/architecture.html

### CODE REVIEW

**Comment by di** [comment]
The docs are also previewed here: https://warehouse--14241.org.readthedocs.build/architecture.html

**Comment by di** [comment]
The only thing missing here I think is that there should probably be a "Redis" component for uploads as well, because this is how we handle rate-limiting for all endpoints, including uploads.

**Comment by miketheman** [comment]
> The only thing missing here I think is that there should probably be a "Redis" component for uploads as well, because this is how we handle rate-limiting for all endpoints, including uploads.

Added!

**Comment by miketheman** [comment]
> would it make more sense for this to be added to our docs at [docs.pypi.org](https://docs.pypi.org/) instead?

I considered this, and didn't know the right answer. I thought about how most of the information is relevant to a warehouse developer (and others). The docs.pypi.org site seems more end-user-focused. I'm happy to put it whereever it makes most sense - but this felt more correct to me.

**Comment by di** [comment]
I think that delineation is good enough for me, for now. Thanks!

**Review by di — APPROVED** [review]

**Pull request merged**
