### PR TITLE
[WIP] Switch from Celery to Dramatiq

### LINKED ISSUE #3492: Celerybeat Cleanup Error
```
worker_1         | Traceback (most recent call last):
worker_1         |   File "/opt/warehouse/lib/python3.6/site-packages/celery/beat.py", line 320, in apply_async
worker_1         |     **entry.options)
worker_1         |   File "/opt/warehouse/src/warehouse/tasks.py", line 95, in apply_async
worker_1         |     return super().apply_async(*args, **kwargs)
worker_1         |   File "/opt/warehouse/lib/python3.6/site-packages/celery/app/task.py", line 518, in apply_async
worker_1         |     check_arguments(*(args or ()), **(kwargs or {}))
worker_1         | TypeError: backend_cleanup() takes 0 positional arguments but 1 was given
worker_1         |
worker_1         | During handling of the above exception, another exception occurred:
worker_1         |
worker_1         | Traceback (most recent call last):
worker_1         |   File "/opt/warehouse/lib/python3.6/site-packages/celery/beat.py", line 222, in apply_entry
worker_1         |     result = self.apply_async(entry, producer=producer, advance=False)
worker_1         |   File "/opt/warehouse/lib/python3.6/site-packages/celery/beat.py", line 328, in apply_async
worker_1         |     entry, exc=exc)), sys.exc_info()[2])
worker_1         |   File "/opt/warehouse/lib/python3.6/site-packages/vine/five.py", line 178, in reraise
worker_1         |     raise value.with_traceback(tb)
worker_1         |   File "/opt/warehouse/lib/python3.6/site-packages/celery/beat.py", line 320, in apply_async
worker_1         |     **entry.options)
worker_1         |   File "/opt/warehouse/src/warehouse/tasks.py", line 95, in apply_async
worker_1         |     return super().apply_async(*args, **kwargs)
worker_1         |   File "/opt/warehouse/lib/python3.6/site-packages/celery/app/task.py", line 518, in apply_async
worker_1         |     check_arguments(*(args or ()), **(kwargs or {}))
worker_1         | celery.beat.SchedulingError: Couldn't apply scheduled task celery.backend_cleanup: backend_cleanup() takes 0 positional arguments but 1 was given
```

I assume this is an integration issue with how the warehouse <-> celery integration happens. Not sure what it's actual affect is though.

### LINKED ISSUE #4561: pypi search fails
I uploaded two projects with twine to pypi.org, after testing at test.pypi.org.
Both projects install correctly from pypi with pip, but one of them does not show up in pypi search.

In browsers Firefox and Safari:

https://pypi.org/search/?q=PairedCompCalc
finds "0 projects for PairedCompCalc", 
but

https://pypi.org/project/PairedCompCalc
shows my project description page correctly.

https://pypi.org/search/?q=samppy
finds my project correctly.

After I log in to pypi.org, or test.pypi.org, both projects PairedCompCalc and samppy show up correctly in my project list.

Both project searches work correctly on test.pypi.org

**My Platform**
Mac OS 10.13.6
Firefox 61.0.2
Safari 11.1.2

### PR DESCRIPTION
**Pull request by dstufft**
This switches us from using Celery to Dramatiq for our asynchronous task worker. It will still use SQS as a queue for these tasks. The API has been kept largely the same, except for:

* Sending uses ``request.task(...).send(...)`` instead of ``request.task(...).delay(...)``.
* You no longer manually manage retries, the system just retries by default.
* Task binding is no longer a thing.
* All tasks get passed `request` as their first object.

Things that still need to be done:

- [ ] Implement suport for periodic tasks
  - Dramatiq doesn't support this by default, so we're going to need our own scheduler implementation. That's somewhat disappointing, but not the end of the world.
- [x] Hot Reloading of Dramatiq when code changes.
- [x] Configuration
  - This includes handling "real" URLs for SQS.
  - Handle the Queue name (specified on the actor, defaults to `default`).
- [x] Add metrics
- [x] Ensure Sentry works.
- [ ] Fix Static file compiling that broke somehow (``EMFILE``?).
- [x] Ensure no references to celery exist in code base.
- [ ] Tests

Fixes #4561
Fixes #3492

### CODE REVIEW

**Comment by yeraydiazdiaz** [comment]
I was just trying out Dramatiq and noticed [this note about scheduling](https://dramatiq.io/cookbook.html#scheduling) which may help with the first point on the list.

**Comment by di** [comment]
> Dramatiq doesn't support this by default, so we're going to need our own scheduler implementation. That's somewhat disappointing, but not the end of the world.

There's now an example of using APScheduler with Dramatiq here: https://dramatiq.io/cookbook.html#scheduling

**Comment by di** [comment]
(Just realized this is the same comment @yeraydiazdiaz left 🤦 )

**Comment by dstufft** [comment]
This has bitrotted to the point I don't think it's useful anymore.

**Pull request closed without merging**
