### PR TITLE
Make OIDC columns non-nullable

### PR DESCRIPTION
**Pull request by di**
Extracted from https://github.com/pypi/warehouse/pull/13272

### CODE REVIEW

**Review by ewdurbin — APPROVED** [review]
only a question, but if we are enforcing these in DB shouldn't we be at least attempting to enforce them in the application?

**Comment by di** [comment]
They are all required fields for the forms that create these models. Is that what you mean?

**Comment by ewdurbin** [comment]
> They are all required fields for the forms that create these models. Is that what you mean?

Yah, just curious what spurred this I guess. Did nulls trickle through?

**Comment by di** [comment]
No, just being explicit, because we're about to add a nullable field to this model.

**Comment by ewdurbin** [comment]
👍👍👍

**Pull request merged**
