### PR TITLE
Add Korean locale to languages

### PR DESCRIPTION
**Pull request by cpprhtn**
Merry Christmas

Pypi Korean translation progress has reached 100%.

Can you add Korean pages to the footer?

THANKYOU :)

### CODE REVIEW

**Comment by cpprhtn** [comment]
#15117 
The related issue number.

**Review by miketheman — APPROVED** [review]
Happy holidays, and thanks for working through this effort!

**Comment by di** [comment]
Reminder to also do step 4 and 5 here: https://warehouse.pypa.io/translations.html#adding-a-newly-completed-translation

**Comment by miketheman** [comment]
> Reminder to also do step 4 and 5 here: [warehouse.pypa.io/translations.html#adding-a-newly-completed-translation](https://warehouse.pypa.io/translations.html#adding-a-newly-completed-translation)

Thanks, done here: https://github.com/pypi/infra/pull/189

**Comment by cpprhtn** [comment]
Thank You
@miketheman and @di

**Pull request merged**
