### PR TITLE
pre-compile warehouse module in docker build

### PR DESCRIPTION
**Pull request by ewdurbin**
In local testing this resulted in a >50% reduction in startup time for the application on a fresh container launch!

Shoutout to @miketheman for the idea.

Before:

```
chungus:warehouse ee$ docker build . -t warehouselocal
docker run -it warehouselocal bash
root@317afce61628:/opt/warehouse/src# time python -m warehouse
Usage: python -m warehouse [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  classifiers    Manage the Warehouse Malware Checks.
  db             Manage the Warehouse Database.
  observations   Group for observation commands.
  organizations  Group for organizations commands.
  projects       Group for projects commands.
  search         Manage the Warehouse Search.
  shell          Open up a Python shell with Warehouse preconfigured in it.
  sponsors       Manage operations on top of sponsors.
  storages       Manage the Warehouse Storages.

real	0m3.858s
user	0m3.547s
sys	0m0.311s
```

After:

```
chungus:warehouse ee$ docker build . -t warehouselocal
docker run -it warehouselocal bash
root@f3420dce6bef:/opt/warehouse/src# time python -m warehouse 
Usage: python -m warehouse [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  classifiers    Manage the Warehouse Malware Checks.
  db             Manage the Warehouse Database.
  observations   Group for observation commands.
  organizations  Group for organizations commands.
  projects       Group for projects commands.
  search         Manage the Warehouse Search.
  shell          Open up a Python shell with Warehouse preconfigured in it.
  sponsors       Manage operations on top of sponsors.
  storages       Manage the Warehouse Storages.

real	0m1.587s
user	0m1.360s
sys	0m0.227s
```

### CODE REVIEW

**Review by miketheman — APPROVED** [review]
Excellent!

**Comment by ewdurbin** [comment]
Hmmmm, needs a lil reconsideration for the `nobody` situation in prod, hold.

**Comment by ewdurbin** [comment]
😮‍💨 lol I was wrong. I wasn't actually testing the container resulting from the image build :)

**Comment by miketheman** [comment]
For funsies, I ran this through `hyperfine` to exercise the containers 10 runs per type, producing these results on my laptop:

I built two image, labelled: test (previous behavior) and west (with the new change).
I then named the tests better as `no-compile` and `compiled` so the output is much clearer:

```shellsession
$ hyperfine \
    -n no-compile 'docker run --rm warehouse:docker-compose-test python -m warehouse --help' \
    -n compiled 'docker run --rm warehouse:docker-compose-west python -m warehouse --help'
Benchmark 1: no-compile
  Time (mean ± σ):      5.820 s ±  0.193 s    [User: 0.013 s, System: 0.009 s]
  Range (min … max):    5.573 s …  6.155 s    10 runs

Benchmark 2: compiled
  Time (mean ± σ):      2.491 s ±  0.035 s    [User: 0.012 s, System: 0.008 s]
  Range (min … max):    2.449 s …  2.541 s    10 runs

Summary
  compiled ran
    2.34 ± 0.08 times faster than no-compile
```

**Pull request merged**
