### PR TITLE
Cover some more human-friendly interpreter tags

### PR DESCRIPTION
**Pull request by di**

### CODE REVIEW

**Comment by di** [comment]
cc @alex I think this is the best we can do here

**Review by alex — APPROVED** [review]
lol. great stuff.

**Review by miketheman — APPROVED** [review]
Good progress!

I still can't shake the feeling that this probably should be part of `packaging`'s responsibility - maybe this code can be removed if/when `packaging` adopts it for wider use.

**Comment by alex** [comment]
I love when someone else writes code instead of me :-) A meta-point is that these tags aren't _really_ designed for parsing in this way. The way pip decides which are viable is that it produces a list of every tag that might be valid for a given interpreter.

**Comment by di** [comment]
I'm not sure this belongs in `packaging`, since that library is mostly an implementation of various standards, and this transformation is definitely not standardized.

**Pull request merged**
