### PR TITLE
Add GitLab Trusted Publishing docs

### PR DESCRIPTION
**Pull request by facutuesca**
PR to merge into this other PR's branch: https://github.com/pypi/warehouse/pull/15192
Adds the GitLab trusted publishing docs. The feature itself is implemented in https://github.com/pypi/warehouse/pull/15275.

cc @woodruffw

### CODE REVIEW

**Review by woodruffw — APPROVED** [review]
LGTM! I'm okay with leaving the TODOs in for now, since this is going into another WIP branch that'll need subsequent updates anyways.

**Comment by woodruffw** [comment]
Just to highlight for review: this is for merge into `pypi:more-oidc-docs`, **not** `pypi:main`!

**Comment by di** [comment]
Let's get the screenshots added here before we merge this (and after we merge #15275) so we can review this in one pass.

**Review by woodruffw — APPROVED** [review]
LGTM, thanks @facutuesca!

**Pull request merged**
