### PR TITLE
tests, warehouse: disable egg uploads

### LINKED ISSUE #10653: Deprecate .egg uploads
Currently PyPI accepts uploads for two distribution types: source distributions, and built distributions. PyPI accepts two built distribution types: wheels and eggs:

https://github.com/pypa/warehouse/blob/7732f2fb9eb0b1da032731d926a094f5f5d1488f/warehouse/forklift/legacy.py#L542

Eggs have never been widely used and have been far outpaced by wheels in recent years:

Wheels vs Eggs

Some additional details:
* As of Dec 2021, eggs have accounted for less than 1% of built distribution uploads. 
* `pip` deprecated the `--egg` command in 2016: https://github.com/pypa/pip/issues/1749
* `setuptools` deprecated the `bdist_egg` command in https://github.com/pypa/setuptools/pull/1764
* `build` only supports wheels for built distributions: https://pypa-build.readthedocs.io/en/latest/#python--m-build---wheel

### PR DESCRIPTION
**Pull request by woodruffw**
**DO NOT MERGE UNTIL AUGUST 1**

Also removes the PEP 715 notice emails, since they'll cease to serve any purpose once eggs can't be uploaded.

Closes #10653.

### CODE REVIEW

**Comment by di** [comment]
I wonder if we want to provide a specific error message when someone tries to upload an egg indicating that it's deprecated rather than just an invalid file? I think it's probably likely we haven't actually been able to inform everyone that might try to upload an `.egg` in the future.

**Comment by di** [comment]
@woodruffw Ah, I missed that change. I suppose that should be sufficient!

**Comment by woodruffw** [comment]
This is updated and good to go by tomorrow!

**Review by di — APPROVED** [review]
🐣

**Comment by miketheman** [comment]
Related: https://github.com/pypa/packaging.python.org/pull/1278

**Comment by woodruffw** [comment]
🍳

**Pull request merged**
