### PR TITLE
Add repository name to github section

### LINKED ISSUE #10917: Show repository name, in the GitHub statistics section
**What's the problem this feature will solve?**
Currently, it's not possible to discover the name of the GitHub repository, associated with a project's metadata from the PyPI page directly. It is also occasionally not immediately clear which of the URLs associated with a project is a GitHub URL.

This makes it possible for projects to misrepresent what their GitHub statistics are, by using a more popular Python project's URL on their metadata.

**Describe the solution you'd like**
Change "GitHub statistics:" to instead be "GitHub: {repo-name}". So, for pip, that would be "GitHub: pypa/pip".

This would:

- provide an "obvious thing" to make into a link to the GitHub repository.
- surface this information to help identify projects that are misrepresenting themselves (intentionally or otherwise).

**Additional context**
See https://discuss.python.org/t/14181/, where this was originally proposed.

### PR DESCRIPTION
**Pull request by merwok**
Fixes #10917

### CODE REVIEW

**Review by pradyunsg — COMMENTED** [review]
LGTM, but I'll let one of the admins merge this. :)

**Comment by merwok** [comment]
Do people think it’s a problem if a repo link ends up in the project URLs section and the github stats section?

**Comment by pradyunsg** [comment]
I certainly don't! They both serve distinct functions IMO -- one presenting the preferred language from the package author and another presenting a consistent + at-a-glance view of what the package reports as its URL.

**Comment by di** [comment]
Aside from the other discussion in #10917, this doesn't seem to actually do what's originally requested in that issue:

> Change "GitHub statistics:" to instead be "GitHub: {repo-name}". So, for pip, that would be "GitHub: pypa/pip".

**Comment by merwok** [comment]
Yes, I disagreed with that specific part of the proposal!  Prefer to keep the existing full title, and clarify what we are reading (let’s not assume that everyone understands «some letters slash more letters», «some word hyphen sig», «r slash word», etc 😉)

**Comment by pradyunsg** [comment]
And I think this is perfectly reasonable as well. :)

**Comment by merwok** [comment]
@di @dstufft could you review this?  I can change the code if you both want the format `github: username/repo`, but I do think my version is clearer!

**Pull request closed without merging**
