### PR TITLE
docs/packaging: fix the link to correct page

### PR DESCRIPTION
**Pull request by davidbgk**
https://packaging.python.org/tutorials/distributing-packages/ returns a 404

### CODE REVIEW

**Review by woodruffw — APPROVED** [review]
LGTM in terms of fixing the links; two thoughts:

1. Maybe we need a linkchecker or similar integration test to catch these link breakages proactively?
2. We should confirm that this is the link we want to use: it looks like the appropriate successor page, but it also uses `setup.py` instead of a more modern packaging flow (with e.g. `pyproject.toml`). But maybe that can be a follow-up, since it's good to just fix the link for now.

**Comment by woodruffw** [comment]
@davidbgk Thanks for the fixes here! Could you bring this branch up-to-date with `main`?

**Comment by miketheman** [comment]
> * Maybe we need a linkchecker or similar integration test to catch these link breakages proactively?

Good idea - `make -C docs/dev/ linkcheck` from the repo root runs Sphinx's built-in link checker. We already have a directive for links we expressly do NOT want to check, see here:
https://github.com/pypi/warehouse/blob/55476f39266473e49d21a3a8e64b7cda4d71fdbf/docs/dev/conf.py#L56-L61

**Comment by miketheman** [comment]
Another general thought specific to the packaging docs site is that they also use [interspinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html), so in theoiry we could as well. Here's an example config from twine: https://github.com/pypa/twine/blob/fe1885f2bf896c1852dedea7733a582c5718bbbc/docs/conf.py#L279-L282
and an example of usage: https://github.com/pypa/twine/blob/fe1885f2bf896c1852dedea7733a582c5718bbbc/docs/index.rst?plain=1#L180

If we use intersphinx references, and the remote **references** remain stable, then as URLs change our would update as well.

**Comment by woodruffw** [comment]
This is now a subset of #15265 (sorry for the confusion here -- I missed that #15224 was essentially a duplicate report).

**Comment by woodruffw** [comment]
Done with #15265, sorry again for the confusion here!

**Comment by davidbgk** [comment]
Not super contributor friendly but glad it's fixed 👍

**Pull request closed without merging**
