### PR TITLE
Restore "Refactoring multiple parts of the dockerfile (#10004)"

### PR DESCRIPTION
**Pull request by ewdurbin**
Reverts pypa/warehouse#10020

### CODE REVIEW

**Comment by ewdurbin** [comment]
HOLD FOR: upgrade to BuildKit compatible builders in deployment pipeline.

**Comment by miketheman** [comment]
The underlying code has changed a fair amount since this was introduced and no longer merged cleanly.

I think there's still good ideas on leveraging cache mounts, but they rely on BuildKit being available during deployment. @ewdurbin is this something we still want to entertain?

**Comment by ewdurbin** [comment]
absolutely want to entertain this. getting us up to a more recent container runtime that supports buildkit is a priority in the coming months.

**Comment by ewdurbin** [comment]
I thought it was just the docker service that needed BuildKit, but turns out its the client too.

Cabotage interacts with the docker build hosts via docker-py which notably does not support BuildKit. ref https://github.com/docker/docker-py/issues/2230

So this remains blocked even after getting our builder upgraded 😅

**Comment by ewdurbin** [comment]
We have a buildkit enabled deployment pipeline! I am closing this in favor of a new implementation to avoid all the deltas that have been introduced.

**Pull request closed without merging**
