### PR TITLE
feat(admin): views for per-project malware reports with verdicts

### PR DESCRIPTION
**Pull request by miketheman**
Signed-off-by: Mike Fiedler <miketheman@gmail.com>

### CODE REVIEW

**Review by ewdurbin — COMMENTED** [review]
Overall this looks great! I really like the simple actions surfaced at the bottom of the aggregated view for a project.

**EDIT: Below is incorrect, I was looking at the `is_dependency_confusion` tab. Confused indeed.**

<details>
  <summary>**EDIT: Below is incorrect, I was looking at the `is_dependency_confusion` tab. Confused indeed.**</summary>
The list view seems to have a grouping bug, after generating sample observations locally I noticed that while two projects had 3 reports each, one was being misattributed to the wrong project:

Screenshot 2024-06-07 at 10 07 28 AM
Screenshot 2024-06-07 at 10 07 34 AM


Screenshot 2024-06-07 at 10 09 06 AM
Screenshot 2024-06-07 at 10 09 13 AM

</details>

**Review by ewdurbin — COMMENTED** [review]
This is great, next steps are to interact with the HS ticket or will we still need to respond to each individually?

**Comment by miketheman** [comment]
> This is great, next steps are to interact with the HS ticket or will we still need to respond to each individually?

I captured the need to refactor HS to a service here so we can use it in these views: https://github.com/pypi/warehouse/issues/16010

I'm thinking of deferring that effort for now, and come back to it once we're further along on quarantine - unless you think it's more important for now?

**Review by ewdurbin — APPROVED** [review]
got it. just worried about keeping things "in sync" and the potential for missed responses to reporters, but since you're the primary one working malware reports I trust you on the ergonomics.

**Pull request merged**
