### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by sadikkuzu**
* recieved -> received

### CODE REVIEW

**Comment by sadikkuzu** [comment]
Hi @ewdurbin 
Could you please review this PR?
Thanks in advance

**Comment by di** [comment]
@sadikkuzu Note that you have test failures here.

I think that we will want to leave the `warehouse.token_leak.github.recieved` typo as-is. This is the tag for our metrics pipeline and changing it will create a break in the historical metrics.

**Comment by sadikkuzu** [comment]
ok, i give up.

**Comment by sadikkuzu** [comment]
If I do so, there won't be any diff.
That's why I closed the pr.
Thanks for your patience.
Have a nice day.
Happy coding! ✨

**Comment by di** [comment]
Not at all! [warehouse/warehouse/integrations/github/utils.py](https://github.com/pypi/warehouse/blob/53cee806b773b16b550a58843e77659bf0cf1cfd/warehouse/integrations/github/utils.py#L108) is a different file than [tests/unit/integration/github/test_utils.py](https://github.com/pypi/warehouse/pull/12266/files#diff-e057e2760ad8ebfb168e9075c47841c8aaf2417d4f2bcf463ec21a1bb54f42ab) -- we have to update both to get the tests to pass.

**Comment by ewdurbin** [comment]
Superseded by #12983 since the fork repository is gone.

**Pull request closed without merging**
