### PR TITLE
Revert "Return `Macaroon` alongside `User` in `MacaroonSecurityPolicy…

### PR DESCRIPTION
**Pull request by di**
….identity` (#15581)"

This reverts commit 862a451bab1f0ccb61ce576fd0026f8132d06054.

I believe this is the cause of https://github.com/pypi/warehouse/issues/15586 and possibly https://github.com/pypi/support/issues/3740.

cc @facutuesca @woodruffw

### CODE REVIEW

**Review by miketheman — APPROVED** [review]

**Comment by di** [comment]
And here when uploading a new release to an existing project: https://github.com/pypi/warehouse/blob/862a451bab1f0ccb61ce576fd0026f8132d06054/warehouse/macaroons/caveats/__init__.py#L107-L108

**Comment by di** [comment]
(Both with account-wide API tokens)

**Comment by webknjaz** [comment]
xref https://github.com/pypa/gh-action-pypi-publish/issues/222

**Comment by woodruffw** [comment]
Thanks for the ping, sorry for the headache here. I totally forgot about those instance checks; will look into a more complete patch now.

(And thanks @webknjaz for triaging on your end!)

**Comment by woodruffw** [comment]
Opened https://github.com/pypi/warehouse/pull/15590 as a draft for this, looking at tests now :slightly_smiling_face:

**Pull request merged**
