### PR TITLE
Create user facing documentation structure

### PR DESCRIPTION
**Pull request by ewdurbin**
Uses [mkdocs](https://www.mkdocs.org) for building https://docs.pypi.org/

This will serve as the location for user-facing documentation moving forward. We should begin separating developer docs from the /docs directory, and @s-mm will be adding documentation for organization accounts here.

### CODE REVIEW

**Comment by ewdurbin** [comment]
We'll have some very PyPI specific docs relating to Organizations and any other paid-features down the line. That's the main driver for this docset.

**Comment by di** [comment]
> Or do we think that PyPI has docs that should be distinct from the overall packaging docs?

IMO, docs like https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/ are already somewhat out of place on p.p.o, but docs about PyPI-specific features would be even more out of place.

Additionally, I think there's an advantage to keeping docs alongside the code in one repo, as it makes it easier to keep them accurate and up to date.

**Comment by dstufft** [comment]
👍

**Comment by ewdurbin** [comment]
this is semi-blocked on https://github.com/readthedocs/readthedocs.org/issues/8234.

as is there is no clean way to host multiple RTD projects out of a single repo/branch.

**Comment by humitos** [comment]
I arrived at this issue while reading your comment and PR on Read the Docs.

> this is semi-blocked on [readthedocs/readthedocs.org#8234](https://github.com/readthedocs/readthedocs.org/issues/8234).
> 
> as is there is no clean way to host multiple RTD projects out of a single repo/branch.

I noted from the description that you are using MkDocs, so I'm not sure if it's currently possible to do this. However, the official Read the Docs user and developer documentation use a Sphinx extension to allow us this use case:

* https://dev.readthedocs.io/
* https://docs.readthedocs.io/

The Sphinx extension is https://github.com/readthedocs/sphinx-multiproject/

I don't think this will solve your problem, but maybe gives you an idea for a potential workaround and unblock you. I hope it helps 😄

**Comment by humitos** [comment]
Another potential immediate solution for this could be using `build.commands` (https://docs.readthedocs.io/en/latest/build-customization.html) and decide what commands execute depending on the project's slug (`READTHEDOCS_PROJECT` environment variable)

```yaml
# .readthedocs.yaml
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - |
        if [ "$READTHEDOCS_PROJECT" = "developer" ] ;
        then
          cd docs/developer;
          mkdocs build;
          mv _build/html ../_readthedocs/html;
        fi
  - |
      if [ "$READTHEDOCS_PROJECT" = "user" ] ;
        then
          cd docs/user;
          mkdocs build;
          mv _build/html ../_readthedocs/html;
        fi
```

I grabbed this idea from https://github.com/readthedocs/readthedocs.org/issues/8811#issuecomment-1178040466. Let me know that could work for now.

**Comment by humitos** [comment]
He, I just saw that you are fighting with the shell in YAML. I've been there as well, and it was frustrating 😞 . Maybe you can follow this example from our docs that _it's working_ already. It's hard to tell you what are the syntax issues you are having in yours, tho

**Comment by ewdurbin** [comment]
yeah, struggling indeed! getting confused since running these in a true `/bin/sh` on ubuntu-22.04 works 😅

**Comment by ewdurbin** [comment]
@humitos given that https://github.com/pypi/warehouse/pull/12953/commits/50f591b48fe77667d67c63e3971fbc21b40332d1 failed and https://github.com/pypi/warehouse/pull/12953/commits/8e06fdc9dc8475b00f097c1e76ee3436aedf6ff5 worked... it seems there is something different in the handling of shell commands in `build.jobs` versus `build.commands`

**Comment by humitos** [comment]
🤯 -- I have no idea what could be happening. It looks weird to me at simple sight. _In theory_, there shouldn't be any differences.

* code for `build.jobs`: https://github.com/readthedocs/readthedocs.org/blob/f4215c5516eaa07c15afe49abdf1bb7a1a34655a/readthedocs/doc_builder/director.py#L292-L333
* code for `build.commands`: https://github.com/readthedocs/readthedocs.org/blob/f4215c5516eaa07c15afe49abdf1bb7a1a34655a/readthedocs/doc_builder/director.py#L335-L370

I'm closing my day now because I'm super tired, but I'll jump into this tomorrow's morning with fresh eyes. Hopefully, I can give you a better answer.

**Comment by ewdurbin** [comment]
https://github.com/pypi/warehouse/pull/12953/commits/8a79c92ec635719d10088c5bdf98d344b323c406 indicates that its a difference in the environments that the commands are run.

post_checkout is the only job run in the `vcs_environment`, all subsequent jobs are run in the `build_enviornment` just like `build.command`.

**Comment by ewdurbin** [comment]
I'm going to remove the deployment portion of this and merge so @s-mm can begin opening PRs against the user-docs directory for organization documentation.

When read the docs supports our use case, we will revisit deployment.

**Comment by humitos** [comment]
@ewdurbin today I opened a PR that I think it will solve the issue you are having with the script syntax error: https://github.com/readthedocs/readthedocs.org/pull/10119. It's under review now, but it has high changes to get deployed next Tuesday 🙏🏼

**Comment by ewdurbin** [comment]
thanks @humitos, is there any way we'll know when it deploys other than tryin' it out?

**Comment by humitos** [comment]
@ewdurbin it's already merged -- It's going to be deployed next Tuesday at 5PM CET

**Comment by ewdurbin** [comment]
> @ewdurbin it's already merged -- It's going to be deployed next Tuesday at 5PM CET

Nice! I'll get a follow-up PR for this one ready after it is merged. :) Thank you!

**Comment by di** [comment]
@ewdurbin Are you OK with this change to the directory structure here? I think this will make it a little more clean/organized, especially when we add another docsite: https://github.com/pypi/warehouse/compare/docs_pypi_org...docs_pypi_org-patch

**Comment by ewdurbin** [comment]
absolutely, send it!

**Review by di — APPROVED** [review]

**Comment by di** [comment]
@ewdurbin This should be good to merge.

**Comment by ewdurbin** [comment]
Thank you for the tidying!

**Pull request merged**
