### PR TITLE
feat: support username autocomplete in forms

### PR DESCRIPTION
**Pull request by miketheman**
When adding a collaborator to a project or organization, support typing
in a few characters to get the top 10 results.

Uses https://www.npmjs.com/package/stimulus-autocomplete

Resolves https://github.com/pypi/warehouse/issues/2746

Includes lint command fix.

### CODE REVIEW

**Comment by miketheman** [comment]
What it looks like (I'm no CSS wizard, but I did what I thought worked out)

https://github.com/pypi/warehouse/assets/529516/3bab0390-6be9-4c0d-ab73-62754f6d276c

**Review by di — COMMENTED** [review]
Wow, this is super nice! I like how simple Stimulus makes this.

The only thing I'd suggest is adding a rate limiter around the `accounts_search` view, maybe 100 req/hr per IP? (Also, I'm curious whether the autocomplete will degrade gracefully with a `429` response)

**Comment by di** [comment]
Also, looking at some prior art, we might want to crib adding avatars and full names (if available) from GitHub:

image

Maybe even shortening it to 5 users?

**Comment by miketheman** [comment]
> The only thing I'd suggest is adding a rate limiter around the `accounts_search` view, maybe 100 req/hr per IP? (Also, I'm curious whether the autocomplete will degrade gracefully with a `429` response)

I'm not really sure how we do view-based rate limiters today - any pointers? It seems like the majority of the ratelimiters we have require some level of interaction with a service? 
We require the user to be logged in, so that's not *nothing*.

> Maybe even shortening it to 5 users?

I like adding names if they've got em. And our gravatar implementation calls our camo, so I'll add that, but can't confirm that the images are correct since my local camo doesn't work to proxy to their service for some reason? (haven't dug too far into it).

On the list design, GitHub fetches 10, but shows the first 5 and scrolls. I don't think I'm going to tackle building a popup/overlaid list with scroll. Happy to change to 5 instead if you prefer.

**Comment by di** [comment]
Here's an example of how the ratelimiters could be used: https://github.com/pypi/warehouse/blob/d1b1581622090ea3fc60d777160547d5e0bfb284/warehouse/accounts/views.py#L1349-L1362

**Review by di — APPROVED** [review]

**Pull request merged**
