### PR TITLE
misc: fix some sentry captures

### PR DESCRIPTION
**Pull request by woodruffw**
These were using `fingerprint` incorrectly;
I've removed their custom scopes and made them
use the top-level APIs instead, since the scope
isn't adding much more.

### CODE REVIEW

**Review by miketheman — APPROVED** [review]
I'm fine with these, however I wonder if we'll see dual-reporting for the same issue, and thus not need a `capture_message()` call alongside `capture_exception()`

**Comment by woodruffw** [comment]
> I'm fine with these, however I wonder if we'll see dual-reporting for the same issue, and thus not need a `capture_message()` call alongside `capture_exception()`

Yeah, I was wondering about that -- if this is too noisy in practice, I can drop it to just the `capture_exception` 🙂

**Comment by di** [comment]
If `capture_exception` is properly discerning/grouping between different exceptions, I don't see a reason to use `capture_message`.

**Comment by woodruffw** [comment]
> If `capture_exception` is properly discerning/grouping between different exceptions, I don't see a reason to use `capture_message`.

Cool, removing then!

**Comment by di** [comment]
Although... IIRC the reason we were using `capture_message` is because this wasn't happening? How is `capture_exception` here any different than just letting the exception raise?

**Comment by woodruffw** [comment]
Ah, that rings a bell -- yeah, I think the issue here was that some of these exceptions were `ValueError` and similar, which ended up being hard to distinguish. 

I'll push up what I have here, but another option would be to re-introduce `fingerprint` with correct usage, e.g.:

```python
scope.fingerprint = ["some-distinguishing-key", exc]
```

**Comment by di** [comment]
What is the problem with the current usage of `fingerprint`?

**Comment by woodruffw** [comment]
> What is the problem with the current usage of `fingerprint`?

Apparently `fingerprint` can't be a scalar, so `fingerprint = e` wasn't working when `e` was just an exception:

image

(@miketheman observed this -- maybe it's a recent change in the Sentry API?)

**Comment by di** [comment]
Can't we just do `scope.fingerprint = [e]`?

**Comment by woodruffw** [comment]
> Can't we just do `scope.fingerprint = [e]`?

Yep, that's a lot simpler. Sorry, my brain is thoroughly fried -- I've been at a Homebrew hackathon for the last 72 hours 🙂 

I'll rework this PR...

**Review by di — APPROVED** [review]

**Comment by woodruffw** [comment]
Gentle ping for merge 🙂

**Pull request merged**
