### PR TITLE
docs(attestations): fix example for GitLab CI/CD

### PR DESCRIPTION
**Pull request by nejch**
I was setting up attestations on gitlab.com and had to go through a bit of trial and error, this is just a tiny typo fix to get a working example, as the options should follow the subcommand.

Here's a (condensed) example config that worked for me and the job uploading the attestations:
https://gitlab.com/marge-org/marge-bot/-/blob/main/.gitlab-ci.yml?ref_type=heads#L179-207
https://gitlab.com/marge-org/marge-bot/-/jobs/8456428455

### CODE REVIEW

**Comment by nejch** [comment]
I was also wondering if the `aud` param for `id` could maybe be lowercase to match the `aud: pypi` in `id_tokens` for consistency, since `id` normalizes the aud from the uppercase environment variable. (I was looking at the sources to make sure the exact mapping especially because some things need a `testpypi` override for testing, and for others the naming is just a convention).

 If you agree I can add this to this PR.

```diff
-        # Retrieve the OIDC token from GitLab CI/CD, and exchange it for a PyPI API token
-        - oidc_token=$(python -m id PYPI)
+        # Retrieve the OIDC token from GitLab CI/CD, and exchange it for a PyPI API token
+        - oidc_token=$(python -m id pypi)
```

**Comment by woodruffw** [comment]
> If you agree I can add this to this PR.

Thanks, please add this!

**Review by woodruffw — APPROVED** [review]
Thanks @nejch!

**Comment by nejch** [comment]
Thanks for the super quick review @woodruffw :bow:

**Review by di — APPROVED** [review]
Thanks @nejch!

**Pull request merged**
