### PR TITLE
Issue Resolved : Prefer "critical project" to "2fa required" badge on /manage/projects/

### LINKED ISSUE #11806: Prefer "critical project" to "2fa required" badge on /manage/projects/
On https://pypi.org/manage/projects/ if you have a project which enabled 2fa requirement manually and then became a critical project, it has the 2fa required badge (and not the critical one). I believe the order of this priority should be reversed, and it should show the critical badge.

a) Criticality is functionally a superset of the behavior, it means 2fa is both required now _and_ that it cannot be disabled
b) Criticality gives you some information about the download volume of the project

### PR DESCRIPTION
**Pull request by SamirPS**
I changed the priority to display badge for this issue #11806 

Fixes #11806.

### CODE REVIEW

**Comment by SamirPS** [comment]
@miketheman Here the new one PR for this issue

**Comment by miketheman** [comment]
Thanks! Can one of the Warehouse Committers allow the Actions to run to verify the changes will merge cleanly?

**Comment by SamirPS** [comment]
I have solved the conflicts to merge cleanly into main

**Comment by SamirPS** [comment]
@miketheman I have solved the conflicts and run the actions on my fork ( all actions pass) now waiting for approval.

**Review by miketheman — APPROVED** [review]
I ran through these and confirmed that:

- project only has `owners_require_2fa`, we display "2FA Required"
- project only has `pypi_mandates_2fa`, we display "Critical Project"
- project has both `owners_require_2fa` and `pypi_mandates_2fa`, we display "Critical Project"

Nice work!

**Review by di — APPROVED** [review]

**Comment by SamirPS** [comment]
Thanks @miketheman

**Pull request merged**
