### PR TITLE
Issue resolved : Prefer "critical project" to "2fa required" badge on /manage/projects/

### PR DESCRIPTION
**Pull request by SamirPS**
I changed the priority to display badge for this issue https://github.com/pypi/warehouse/issues/11806

### CODE REVIEW

**Comment by SamirPS** [comment]
@di

**Comment by SamirPS** [comment]
@di ?

**Comment by SamirPS** [comment]
@alex

**Comment by miketheman** [comment]
@SamirPS The actual failing test suite tells us what to do: https://github.com/pypi/warehouse/runs/7585359799?check_suite_focus=true#step:9:532

**Comment by SamirPS** [comment]
> @SamirPS The actual failing test suite tells us what to do: https://github.com/pypi/warehouse/runs/7585359799?check_suite_focus=true#step:9:532

Thanks i just commit the output of make translations and now i wait for the pipeline

**Comment by miketheman** [comment]
@SamirPS Thanks! From the GitHub status, there's now conflicts that need to be resolved - would you mind trying to rebase or merge your branch from the current `main` to identify and resolve?

**Comment by SamirPS** [comment]
> @SamirPS Thanks! From the GitHub status, there's now conflicts that need to be resolved - would you mind trying to rebase or merge your branch from the current `main` to identify and resolve?

@miketheman can you tell me the command to do ?

**Comment by SamirPS** [comment]
@miketheman good now ? because i see other conflits

**Pull request closed without merging**
